# Load in NumPy (remember to run this cell each session before working in any others)

In [1]:
import numpy as np

## The Basics: setting lists

In [2]:
a = np.array([1,2,3], dtype='int32')
# Adding the dtype isn't necessary. We have done this in order to test, in some cells down below, the size/item size etc.
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get dimensions, shapes and such

In [4]:
# Get Dimension
b.ndim

2

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size. Size is the number of elements. Item size is the bytes of each individual item in the list. To get the bytes of the full list, multiply size*itemsize or just use nbytes.
a.nbytes

12

In [9]:
a.size * a.itemsize

12

In [10]:
b.nbytes

48

### Accessing/changing specific elements, rows, columns etc.

In [11]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
c[1, 5]

13

In [13]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [16]:
# Change an element
c[1,5] = 20
print(c)

c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
# 3-d example
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (advice is to work outside in)
d[0,1,1]

4

In [19]:
# Replace
d[:,1,:] = [[9,9],[8,8]]

In [20]:
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different types of arrays

In [21]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
# Any other number. Takes parametres - first the shape (2,2), then the value of the items in the array (99), and optionally you can specify the data type.
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [24]:
# Any other number (full_like), we can take a shape that is already built (in this case, c) and create another array that's the same size and shape. 2nd parametre is value.
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# Another way of doing what we've done just above this block
np.full(c.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal numbers - you're passing integers here, not a tuple.
np.random.rand(4,2,3)

array([[[0.09694987, 0.82754997, 0.16358347],
        [0.8858956 , 0.19047736, 0.09850596]],

       [[0.58384903, 0.8906007 , 0.00309101],
        [0.93430928, 0.2545741 , 0.81793292]],

       [[0.03673522, 0.54728926, 0.18254888],
        [0.16044756, 0.36620252, 0.56519592]],

       [[0.22223417, 0.79765741, 0.88400488],
        [0.71057595, 0.91905206, 0.62816607]]])

In [29]:
# Random decimal numbers to a particular shape
np.random.random_sample(c.shape)

array([[0.30185096, 0.70848842, 0.04356096, 0.23281923, 0.09223762,
        0.63608232, 0.22675969],
       [0.92307842, 0.34395619, 0.83794127, 0.86610217, 0.64032813,
        0.60221595, 0.65632499]])

In [42]:
# Random integer values. With one parameter, that parameter serves as the maximum. With two, they are minimum,maximum.
np.random.randint(3,7, size=(3,3))

array([[4, 3, 5],
       [5, 5, 6],
       [3, 5, 6]])

In [44]:
# Identity matrix (not sure what this is). It will be square.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
# Repeating arrays - this repeats the objects in an array the number of times specified in the second parameter of repeat.
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [55]:
# Alternatively, repeating the array itself. Second parameter of np.repeat is how many times you want it repeated. Note the extra layer of brackets around the arr1 array.
# Also, the specification of 0 for axis is for, I think, that embedding level. So if specified 1 instead of 0, we'd get the same result as above.
# The array has two dimensions, so specifying the axis as 2 throws an error.
arr1 = np.array([[1,2,3]])
r2 = np.repeat(arr1,3, axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
