# Load in NumPy (remember to run this cell each session before working in any others)

In [5]:
import numpy as np

## The Basics: setting lists

In [17]:
a = np.array([1,2,3], dtype='int32')
# Adding the dtype isn't necessary. We have done this in order to test, in some cells down below, the size/item size etc.
a

array([1, 2, 3])

In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get dimensions, shapes and such

In [11]:
# Get Dimension
b.ndim

2

In [12]:
# Get Shape
b.shape

(2, 3)

In [15]:
# Get Type
a.dtype

dtype('int16')

In [18]:
# Get Size
a.itemsize

4

In [21]:
# Get total size. Size is the number of elements. Item size is the bytes of each individual item in the list. To get the bytes of the full list, multiply size*itemsize or just use nbytes.
a.nbytes

12