# Load in NumPy (remember to run this cell each session before working in any others)

In [23]:
import numpy as np

## The Basics: setting lists

In [24]:
a = np.array([1,2,3], dtype='int32')
# Adding the dtype isn't necessary. We have done this in order to test, in some cells down below, the size/item size etc.
a

array([1, 2, 3])

In [25]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get dimensions, shapes and such

In [26]:
# Get Dimension
b.ndim

2

In [27]:
# Get Shape
b.shape

(2, 3)

In [28]:
# Get Type
a.dtype

dtype('int32')

In [29]:
# Get Size
a.itemsize

4

In [30]:
# Get total size. Size is the number of elements. Item size is the bytes of each individual item in the list. To get the bytes of the full list, multiply size*itemsize or just use nbytes.
a.nbytes

12

In [31]:
a.size * a.itemsize

12

In [32]:
b.nbytes

48

### Accessing/changing specific elements, rows, columns etc.

In [33]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
# Get a specific element [r, c]
c[1, 5]

13

In [35]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [37]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [38]:
# Change an element
c[1,5] = 20
print(c)

c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [39]:
# 3-d example
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (advice is to work outside in)
d[0,1,1]

4

In [42]:
# Replace
d[:,1,:] = [[9,9],[8,8]]

In [43]:
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different types of arrays