# Load in NumPy (remember to run this cell each session before working in any others)

https://github.com/KeithGalli/NumPy/blob/master/NumPy%20Tutorial.ipynb

For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

* Determinant
* Trace
* Singular Vector Decomposition
* Eigenvalues
* Matrix Norm
* Inverse
Etc...

In [679]:
import numpy as np

## The Basics: setting lists

In [680]:
a = np.array([1,2,3], dtype='int32')
# Adding the dtype isn't necessary. We have done this in order to test, in some cells down below, the size/item size etc.
a

array([1, 2, 3])

In [681]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get dimensions, shapes and such

In [682]:
# Get Dimension
b.ndim

2

In [683]:
# Get Shape
b.shape

(2, 3)

In [684]:
# Get Type
a.dtype

dtype('int32')

In [685]:
# Get Size
a.itemsize

4

In [686]:
# Get total size. Size is the number of elements. Item size is the bytes of each individual item in the list. To get the bytes of the full list, multiply size*itemsize or just use nbytes.
a.nbytes

12

In [687]:
a.size * a.itemsize

12

In [688]:
b.nbytes

48

### Accessing/changing specific elements, rows, columns etc.

In [689]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [690]:
# Get a specific element [r, c]
c[1, 5]

13

In [691]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [692]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [693]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [694]:
# Change an element
c[1,5] = 20
print(c)

c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [695]:
# 3-d example
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [696]:
# Get specific element (advice is to work outside in)
d[0,1,1]

4

In [697]:
# Replace
d[:,1,:] = [[9,9],[8,8]]

In [698]:
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different types of arrays

In [699]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [700]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [701]:
# Any other number. Takes parametres - first the shape (2,2), then the value of the items in the array (99), and optionally you can specify the data type.
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [702]:
# Any other number (full_like), we can take a shape that is already built (in this case, c) and create another array that's the same size and shape. 2nd parametre is value.
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [703]:
# Another way of doing what we've done just above this block
np.full(c.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [704]:
# Random decimal numbers - you're passing integers here, not a tuple.
np.random.rand(4,2,3)

array([[[0.13816981, 0.94342727, 0.90486818],
        [0.7377881 , 0.39701202, 0.84053207]],

       [[0.22459369, 0.05123663, 0.32866014],
        [0.93270812, 0.0412292 , 0.12794611]],

       [[0.84333187, 0.09084764, 0.54113655],
        [0.81313083, 0.6861768 , 0.75108793]],

       [[0.16389457, 0.47589123, 0.53663083],
        [0.4547136 , 0.35551342, 0.43078142]]])

In [705]:
# Random decimal numbers to a particular shape
np.random.random_sample(c.shape)

array([[0.53537781, 0.59520856, 0.85089439, 0.55145279, 0.3192649 ,
        0.08754409, 0.40067328],
       [0.58024613, 0.48872854, 0.70907853, 0.20611976, 0.08178394,
        0.75800643, 0.37541315]])

In [706]:
# Random integer values. With one parameter, that parameter serves as the maximum. With two, they are minimum,maximum.
np.random.randint(3,7, size=(3,3))

array([[6, 3, 6],
       [4, 4, 4],
       [5, 4, 5]])

In [707]:
# Identity matrix (not sure what this is). It will be square.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [708]:
# Repeating arrays - this repeats the objects in an array the number of times specified in the second parameter of repeat.
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [709]:
# Alternatively, repeating the array itself. Second parameter of np.repeat is how many times you want it repeated. Note the extra layer of brackets around the arr1 array.
# Also, the specification of 0 for axis is for, I think, that embedding level. So if specified 1 instead of 0, we'd get the same result as above.
# The array has two dimensions, so specifying the axis as 2 throws an error.
arr1 = np.array([[1,2,3]])
r2 = np.repeat(arr1,3, axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [710]:
challengeMatrix = np.zeros((5,5), dtype='int32')
print(challengeMatrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [711]:
challengeMatrix[0,:] = [1]
print(challengeMatrix)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [712]:
challengeMatrix[-1,:] = [1]
print(challengeMatrix)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [713]:
challengeMatrix[[2],2] = [9]
print(challengeMatrix)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 9 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [714]:
challengeMatrix[1:4,[0,-1]] = [1]
print(challengeMatrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [715]:
# A much less elegant way of achieving the above, which was the final step in creating the matrix for the challenge.
challengeMatrix[[1],[0,-1]] = [1]
challengeMatrix[[2],[0,-1]] = [1]
challengeMatrix[[3],[0,-1]] = [1]
print(challengeMatrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [716]:
# Be careful when copying arrays!!!
# What's happening here is that we're not copying the array; we're telling the computer that b points to the same thing that a is pointing to.
# The array isn't copied; you have two variables pointing to the same array.
e = np.array([1,2,3])
f = e
f[0] = 100
print(e)

[100   2   3]


In [717]:
# This is how to do the above properly
e = np.array([1,2,3])
f = e.copy()
f[0] = 100

print(e)
print(f)

[1 2 3]
[100   2   3]


# Mathematics

In [718]:
g = np.array([1,2,3,4])
print(g)

[1 2 3 4]


In [719]:
g + 2 

array([3, 4, 5, 6])

In [720]:
g - 2

array([-1,  0,  1,  2])

In [721]:
g * 2

array([2, 4, 6, 8])

In [722]:
g / 2

array([0.5, 1. , 1.5, 2. ])

In [723]:
h = np.array([1,0,1,0])
g + h

array([2, 2, 4, 4])

In [724]:
g ** 2

array([ 1,  4,  9, 16])

In [725]:
# Take the sin of all values
np.sin(g)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [726]:
# Take the cos of all values
np.cos(g)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear algebra

In [727]:
i = np.ones((2,3))
print(i)

j = np.full((3,2), 2)
print(j)

# Matrix multiply
np.matmul(i,j)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [728]:
# Find the determinant
k = np.identity(3)
print(k)
np.linalg.det(k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

##### Statistics

In [729]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [730]:
np.min(stats)

1

In [731]:
np.min(stats, axis=1)

array([1, 4])

In [732]:
np.max(stats)

6

In [733]:
np.max(stats, axis=1)

array([3, 6])

In [734]:
np.sum(stats)

21

In [735]:
np.sum(stats, axis=0)

array([5, 7, 9])

##### Reorganising Arrays

In [736]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [737]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [738]:
# Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

##### Load data from file

In [739]:
# Note that the data.txt file sits within the project scope, i.e. in the folder with numpypractice.ipynb
# It also sits alongside it.
# By default, the numbers you get will be floats. We convert this into integers manually.

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32') # This does not change the filedata variable, merely represents in in the specified way i.e. as int32 in this case.
filedata = filedata.astype('int32') # Now we have converted the matrix held in the (or pointed to by the) filedata variable into integers properly.
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### Boolean masking and advanced indexing

In [740]:
# Learn where in the filedata the value is greater than fifty
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [741]:
# Index based on where numbers are greater than 50. Returns only those that are.
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [742]:
# You can index with a list in NumPY
l = np.array([1,2,3,4,5,6,7,8,9])
l[[1,2,8]]

array([2, 3, 9])

In [743]:
# Go through all columns and find those containing a number greater than 50
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [744]:
# Find columns where all values are greater than 50 - only one exists
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [745]:
# Same search as above, along rows instead of columns
np.all(filedata > 50, axis=1)

array([False, False, False])

In [746]:
# Multiple conditions
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [747]:
# Opposite of the above, ~ means not true
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [748]:
secondChallengeMatrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(secondChallengeMatrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [749]:
# Correct answer, but different solution. The solution from the video is found below
secondChallengeMatrix[2:4,[0,1]]

array([[11, 12],
       [16, 17]])

In [754]:
secondChallengeMatrix[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [783]:
secondChallengeMatrix[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [793]:
secondChallengeMatrix[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])